# Generated by Django 4.2 on 2023-05-18 19:29

import assitant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assitant', '0002_ta_created_at_ta_created_by_ta_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta',
            name='course',
            field=models.IntegerField(validators=[assitant.models.validate_course]),
        ),
        migrations.AlterField(
            model_name='ta',
            name='course_instructor',
            field=models.IntegerField(validators=[assitant.models.validate_course_instructor]),
        ),
    ]
